# Generated by Django 3.1.7 on 2021-03-05 17:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notification', '0002_auto_20210305_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
